# frozen_string_literal: true

require_relative "../test_helper"

class WGSLTranslatorTest < Test::Unit::TestCase
  test "translates C to WGSL" do
    uniforms = { time: :float }
    helpers = "static inline float helper(float x) { return x * 2.0f; }"
    fragment = "return vec3_new(1.0f, 0.0f, 0.0f);"

    translator = RLSL::WGSL::Translator.new(uniforms, helpers, fragment)
    wgsl = translator.translate

    assert wgsl.include?("// WGSL Shader generated by RLSL")
    assert wgsl.include?("struct Uniforms")
    assert wgsl.include?("time: f32")
    assert wgsl.include?("@compute @workgroup_size(8, 8)")
  end

  test "replaces vec2_new with vec2<f32>" do
    translator = RLSL::WGSL::Translator.new({}, "", "vec2_new(1.0f, 2.0f)")
    wgsl = translator.translate
    assert wgsl.include?("vec2<f32>(1.0f, 2.0f)")
  end

  test "replaces vec3_new with vec3<f32>" do
    translator = RLSL::WGSL::Translator.new({}, "", "vec3_new(1.0f, 2.0f, 3.0f)")
    wgsl = translator.translate
    assert wgsl.include?("vec3<f32>(1.0f, 2.0f, 3.0f)")
  end

  test "replaces math functions" do
    translator = RLSL::WGSL::Translator.new({}, "", "sqrtf(x) sinf(y) cosf(z)")
    wgsl = translator.translate
    assert wgsl.include?("sqrt(x)")
    assert wgsl.include?("sin(y)")
    assert wgsl.include?("cos(z)")
  end

  test "removes static keyword" do
    translator = RLSL::WGSL::Translator.new({}, "static float foo;", "")
    wgsl = translator.translate
    assert_false wgsl.include?("static f32")
  end

  test "handles empty code" do
    translator = RLSL::WGSL::Translator.new({}, nil, nil)
    wgsl = translator.translate
    assert wgsl.include?("@compute @workgroup_size(8, 8)")
  end

  test "generates proper uniform types" do
    uniforms = { time: :float, mouse: :vec2, pos: :vec3, color: :vec4 }
    translator = RLSL::WGSL::Translator.new(uniforms, "", "")
    wgsl = translator.translate

    assert wgsl.include?("time: f32")
    assert wgsl.include?("mouse: vec2<f32>")
    assert wgsl.include?("pos: vec3<f32>")
    assert wgsl.include?("color: vec4<f32>")
  end

  test "replaces float type with f32" do
    translator = RLSL::WGSL::Translator.new({}, "float foo = 1.0;", "")
    wgsl = translator.translate
    assert wgsl.include?("f32 foo = 1.0;")
  end
end

class WGSLIntegrationTest < Test::Unit::TestCase
  test "RLSL.to_wgsl generates WGSL code" do
    wgsl = RLSL.to_wgsl(:test_wgsl) do
      uniforms { float :time }
      helpers(:c) { "" }
      fragment { "return vec3_new(1.0f, 0.0f, 0.0f);" }
    end

    assert_kind_of String, wgsl
    assert wgsl.include?("@compute")
    assert wgsl.include?("time: f32")
  end
end
